### ISSUE TITLE
Support Lombok '@SuperBuilder'

### ISSUE THREAD

**Issue by octopus-prime** [jpa-buddy/documentation#109]
JPA Buddy does not recognize Lombok '@SuperBuilder'.

```
@Entity
@Audited
@AuditOverride(forClass = AbstractEntity.class)
@Getter
@SuperBuilder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Vertrag extends AbstractEntity {

    @Column(length = 9, nullable = false, unique = true)
    private String vertragNr;

    @OneToOne(optional = false)
    private Vereinbarung vereinbarung;
}
```

![image](https://user-images.githubusercontent.com/7620013/202846058-09d0a4f1-4ff7-4212-852d-37fa683c01c9.png)

**Comment by honest-niceman** [comment]
Hey, @octopus-prime! 

Thank you for the feature request! 

This repository is designed exceptionally for the JPA Buddy documentation. For your request, I just created a ticket in our issue tracker. You can track it's status here: https://issues.jpa-buddy.com/issue/JPAB-2399
